'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpVersion='https://quantcast.mgr.consensu.org/tcfv2/CMP_FILE?referer=www.minijogos.com.br'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpVersion;window._qevents=window._qevents||[];(function(){var elem=document.createElement('script');elem.src=(document.location.protocol=="https:"?"https://secure":"http://edge")+".quantserve.com/quant.js";elem.async=true;elem.type="text/javascript";var scpt=document.getElementsByTagName('script')[0];scpt.parentNode.insertBefore(elem,scpt);})();var qcaccount='p-'+'2c7_jN5AFtqg1';window._qevents.push({qacct:qcaccount,source:"choice"});firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #85B300 !important; "
+"   border-color: #85B300 !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #85B300 !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #85B300 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #85B300 !important; "
+"   border-color: #85B300 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #888 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui a, "
+" .qc-cmp-ui .qc-cmp-alt-action { "
+"   color: #141E23 !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #85B300!important; "
+"   border-color: #85B300!important; "
+" } "
+"#qc-cmp2-ui {border-radius:10px}#qc-cmp2-ui .logo-container {margin-bottom:10px !important;width:100%;}#qc-cmp2-ui button {border-radius:30px!important}"
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','zh'];return langs.indexOf(lang)===-1?false:true;};if(isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{'premiumProperties':{'googleWhitelist':[1]},'premiumUiLabels':{},'coreUiLabels':{},'theme':{'uxPrimaryButtonColor':'#85B300','uxSecondaryButtonTextColor':'#888','uxToogleActiveColor':'#85B300','uxLinkColor':'#141E23'},'coreConfig':{'quantcastAccountId':'2c7_jN5AFtqg1','privacyMode':["GDPR"],'hashCode':'1daYDN6K86qrxe0V3MpRoA','publisherCountryCode':'ES','publisherName':'Minijogos','vendorPurposeIds':[2,3,4,5,6,7,8,9,10,1],'vendorFeaturesIds':[1,3,2],'vendorPurposeLegitimateInterestIds':[3,5,7,8,9,2,4,10,6],'vendorSpecialFeaturesIds':[1,2],'vendorSpecialPurposesIds':[1,2],'googleEnabled':true,'consentScope':'service','thirdPartyStorageType':'iframe','consentOnSafari':false,'lang_':autoDetectedLanguage,'displayUi':'always','initScreenBodyTextOption':1,'defaultToggleValue':'off','initScreenRejectButtonShowing':false,'publisherConsentRestrictionIds':[],'publisherLIRestrictionIds':[],'softOptInEnabled':false,'showSummaryView':true,'persistentConsentLinkLocation':3,'displayPersistentConsentLink':false,'uiLayout':'popup','publisherLogo':'https://minijuegos.com/assets/media/consent/header.png','publisherPurposeIds':[1,2],'publisherPurposeLegitimateInterestIds':[],'publisherSpecialPurposesIds':[],'publisherFeaturesIds':[],'publisherSpecialFeaturesIds':[],'stacks':[1,42],'vendorListUpdateFreq':60},'nonIabVendorsInfo':{}});})();